language: python
python:
  - 3.4
  - 3.5
  - 3.6
cache: pip

install:
  - pip install -r requirements.txt
  - pip install -U flake8

script:
  - flake8 .

before_deploy: "python setup.py sdist"
deploy:
  - provider: releases
    api_key:
      secure: ZK3/nNVtUf//5ZZM6CWT3UqDeAH+JHXhu/g3Be591ZUPs82iNySTp+mCkGpWSqj/qF5Str396TfHddmxwppDxh+tfWWY/a38v5PZVVMFwFG65xiwGjIFg/0IJ7WbqAgOZjqzdIkXrILV9jcyl+Jg+VKBcAUvvd9F458RZ3DY+e3mZfMe2O6inHwpbi9JtL2ZzjfKj6+reavHo3vRRRINvb8hFJyA03Pc+ywgEIG3pZNEj+EJBgY8uXP07oRSsBaixe0rRo5N/lYZkRF4fbvMx7CAJsoRbdcgK7J1UVosww6lwAT8GS7kqgyNS2IgFqKu8Quu2h0Oi2sr0PfKZLK0fVB24aDn1SWlv7DvR7vuAUTLNI8b+em/oNz6gGAwLkR6Pyxg31YS7YQFDKquQGwSRlw8DkyQLIi6quyTteH8fFWYqvlMKAw/i6OXu+wcB3PSoOuRVqTq73wawD2zuwfKBdtvpAR9LoQ76SOLy9BEfvrSRMTFzqVZtLn3nXWYIgcv+pd2Ny1kNbKdei93G9z9u3aWW/wXw53qxXc2dbKW9dzmpvIIiTbc+NMHOmVFJvBK/SjEeijzWw3PgWQFyV3XBFLiUkYCcho84LKvXjZkrCLMtEDo9JLPe9xbR+7hHjZg0iE2hxMONdfywM2/9K9gSrO3QPokQlciINrPw2wezzU=
    file_glob: true
    file: dist/geokrety-jsonapi-client-proto-*.tar.gz
    skip_cleanup: true
    on:
      tags: true
      repo: geokrety/geokrety-jsonapi-client-proto
